### ISSUE TITLE
Invalid requests while saving settings

### ISSUE THREAD

**Issue by azurit** [urosevic/head-footer-code#1]
Your plugin is doing invalid POST requests to WordPress while saving settings with both 'HEAD Code' and 'FOOTER Code' set. The problem in POST request is that there are two 'action' parameters and two 'option_page' parameters, for example:

```
option_page=head_footer_code_sitewide_settings&action=update&_wpnonce=c22095e1e6&option_page=head_footer_code_article_settings&action=update&_wpnonce=9428c0e21f....
```

I have never seen such behavior in plain WordPress and also in any other plugin. This is, unfortunately, doing problems with various security tools like modsecurity, which is blocking such requests because there should be only one 'action' parameter.

Can you be so kind and look at this? Thank you.

**Comment by urosevic** [comment]
Thanks for raising this issue @azurit - will be resolved in upcoming release.

**Comment by urosevic** [comment]
Hello @azurit ,

I finally got some time to look after this issue. Until I release new version, are you OKay to test code from the [master](https://github.com/urosevic/head-footer-code) branch and let me know if all now working fine for you?

Cheers,
Aleksandar

**Comment by azurit** [comment]
Looks good! Thank you.

**Comment by urosevic** [comment]
Thanks for confirmation @azurit

The new version [1.2](https://github.com/urosevic/head-footer-code/releases/tag/v1.2) has been released.
